### ISSUE TITLE
[FEATURE] Create query "Create table product"

### ISSUE THREAD

**Issue by stishchenko** [stishchenko/asd-java-intern#38]
**Feature description**
I need to create MySQL query to create table product according to documentstion.

**Expected result**
My result:
CREATE TABLE product(  
  id INT NOT NULL AUTO_INCREMENT,
  supplier_id INT NOT NULL,
  name VARCHAR(45) NOT NULL,
  state VARCHAR(15) NOT NULL DEFAULT 'Created',
  carrency VARCHAR(3) NOT NULL,
  guests INT NOT NULL DEFAULT 1,
  longitude DOUBLE DEFAULT NULL,
  latitude DOUBLE DEFAULT NULL,
  physical_address VARCHAR(255) DEFAULT NULL,
  version TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (supplier_id) REFERENCES party(id)
);

**Comment by rdovgan** [comment]
@stishchenko typo in field "carrency". I've changed to "currency"
Table `product` for `asd_db` scheme was created
