### ISSUE TITLE
[FEATURE] Created query for table price creation

### ISSUE THREAD

**Issue by stishchenko** [stishchenko/asd-java-intern#53]
**Feature description**
The query to create table price.

CREATE TABLE price(  
  id INT NOT NULL AUTO_INCREMENT,
  entity_type VARCHAR(15) NOT NULL,
  entity_id INT NOT NULL,
  name VARCHAR(45) NOT NULL,
  state VARCHAR(15) DEFAULT 'Initial',
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  value DOUBLE NOT NULL,
  currency VARCHAR(3) NOT NULL,
  version TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (entity_id) REFERENCES product(id)
);

**Comment by rdovgan** [comment]
@stishchenko done
