### ISSUE TITLE
[FEATURE] Created query for table fee creation

### ISSUE THREAD

**Issue by stishchenko** [stishchenko/asd-java-intern#55]
**Feature description**
The query to create table fee.

CREATE TABLE fee(  
  id INT NOT NULL AUTO_INCREMENT,
  fee_type TINYINT NOT NULL,
  product_id INT NOT NULL,
  name VARCHAR(15) DEFAULT NULL,
  state VARCHAR(15) DEFAULT 'Initial',
  from_date DATE NOT NULL,
  to_date DATE NOT NULL,
  tax_type TINYINT NOT NULL DEFAULT 1,
  unit TINYINT NOT NULL DEFAULT 1,
  value DOUBLE DEFAULT 0.0,
  value_type TINYINT NOT NULL DEFAULT 1,
  currency VARCHAR(3) NOT NULL,
  version TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (product_id) REFERENCES product(id)
)

**Comment by rdovgan** [comment]
@stishchenko done
