### ISSUE TITLE
[FEATURE] Implement additional methods

### ISSUE THREAD

**Issue by rdovgan** [stishchenko/asd-java-intern#59]
**Feature description**
Need to implement methods and APIs with next functionality:
1) Retrieve and filter all Product records by next parameters: `supplierId`, `name`, `state`
2) Retrieve and filter all Price records by next parameters: `entityType`, `entityId`, `state`
3) Retrieve a list of Price items by date range and filter `fromDate` and `toDate` parameters which fully included in that range
4) Store a list of Price records
5) Retrieve and filter Fee records by next parameters: `feeType`, `productId`, `state`
6) Store a list of Fee records
7) Retrieve a list of Fee items by date range and filter `fromDate` and `toDate` parameters which fully included in that range

**Requirements**
Implemented CRUD methods for services, controllers and MyBatis methods

**Expected result**
Implemented API endpoints in controller, service methods and MyBatis methods

**Need to create a new working branch from `master` repository** ⬅️ ❗️

**Comment by rdovgan** [comment]
@stishchenko please discuss all questions related to this task here in comments

**Comment by stishchenko** [comment]
@rdovgan "Filter by next parameters" mean that I need to create one method to filter by all this parameters depending on getting parameters or different methods for each parameter?

**Comment by rdovgan** [comment]
> @rdovgan "Filter by next parameters" mean that I need to create one method to filter by all this parameters depending on getting parameters or different methods for each parameter?

@stishchenko first option
For each numbered case should be one method
Also, please note that any parameter can be `null`. In this case you should not filter by this parameter

**Comment by rdovgan** [comment]
@stishchenko In `2.` task `entityId` and in `5.` task `productId` parameters are required. In case when you will get it as "wrong" values, you should throw an exception
