### ISSUE TITLE
[FEATURE] Deploy application on a separate server

### ISSUE THREAD

**Issue by rdovgan** [stishchenko/asd-java-intern#60]
**Feature description**
1. Connect to your Virtual Server

> Server Address: `20.127.210.163`
> User: `stishchenko`
> Password: ask me in Slack

Use next command to connect to the server: `ssh stishchenko@20.127.210.163`

2. Install GIT
3. Install Java 11 and configure $JAVA_HOME path
4. Install Maven
5. Clone your project from repository
6. Deploy your project using `mvnw spring-boot:run` command

**Expected result**
Deployed application on a Virtual server with working endpoints

**Need to create a new working branch from `master` repository**

**Comment by stishchenko** [comment]
@rdovgan I have found old version of GIT on virtual server. Do I need to delete this and setup newer version or only setup GIT one more time or left current version?

**Comment by rdovgan** [comment]
@stishchenko it's not necessary
