### ISSUE TITLE
[FIX] Fix `readPricesByDateRange` method

### ISSUE THREAD

**Issue by rdovgan** [stishchenko/asd-java-intern#91]
**Bug description**
Need to fix `readPricesByDateRange` method. Please add a `productId` parameter and retrieve price items using it

**Expected result**
Need to filter price items by `productId`

**Actual result**
Price items retrieves by date range only

**Comment by stishchenko** [comment]
@rdovgan Can I do the same refactoring for method readFeesByDateRange in for fee table? It has the same organizasion as readPricesByDateRange.
